# Generated by Django 4.0.2 on 2022-02-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('data_wprowadzenia', models.DateTimeField(blank=True, null=True)),
                ('isn', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('lokalizacja_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('nr_ubytku', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('powod_ubytkowania_id', models.TextField(blank=True, null=True)),
                ('rok_wydania', models.DateField(blank=True, null=True)),
                ('symbol_ukd', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('tematyka_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('tom', models.CharField(blank=True, max_length=150, null=True)),
                ('typ_publikacji_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('tytul', models.CharField(max_length=350)),
                ('wartosc', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('wydawca', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
